active: local


shared:
  datasets:
    ustc-tfc2016:
      root-path:

  methods:
    # GLADS 数据预处理
    glads:
      module: preprocessor.impl.glads
      class: GladsPreprocessor
    capsule:

    # USTC 数据集统计分析
    ustc-tfc2016-statistics:
      # 数据分析器所在的模块
      module: preprocessor.impl.ustc_statistics
      # 数据分析器的类名
      class: UstcStatistics


  preprocessors:
    # USTC 数据集统计
    ustc-tfc2016-statistics:
      # 使用的方法
      method: ustc-tfc2016-statistics
      # 使用的数据集
      dataset: ustc-tfc2016
      output-path: ./datasets/USTC-Statistics

    ustc-tfc2016-capsule:
      number-workers: 2
      kwargs:
        M: 20
        N: 1000

# MARK: - 本地测试配置
local:
  datasets:
    ustc-tfc2016:
      root-path: ./datasets/USTC-example
  preprocessors:
    ustc-tfc2016-capsule:
      method: capsule
      dataset: ustc-tfc2016
      output-path: ./datasets/USTC-example-capsule-20-1000
    glads-ustc:
      method: glads
      dataset: ustc-tfc2016
      output-path: ./datasets/USTC-Glads

# MARK: - 学校服务器配置
school-server:

  datasets:
    ustc-tfc2016:
      root-path: /home/wangc/datasets/USTC-TFC2016
    isc-vpn-2016:
      root-path: /home/wangc/datasets/ISC-VPN-nonVPN-2016
  preprocessors:
    # USTC 数据集统计
    ustc-tfc2016-statistics:
      # 使用的方法
      method: ustc-tfc2016-statistics
      # 使用的数据集
      dataset: ustc-tfc2016
      output-path: /home/wangc/datasets/USTC-Statistics
    isc-vpn-2016-statistics:
      method: ustc-tfc2016-statistics
      dataset: isc-vpn-2016
      output-path: /home/wangc/datasets/ISC-VPN-nonVPN-2016-Statistics
    glads-ustc:
      method: glads
      dataset: ustc-tfc2016
      output-path: /home/wangc/datasets/USTC-Glads
    glads-isc-vpn:
      method: glads
      dataset: isc-vpn-2016
      output-path: /home/wangc/datasets/ISC-VPN-nonVPN-2016-Glads