active: local


shared:
  datasets:
    ustc-tfc2016:
      root-path:

  methods:
    glads:

    capsule:

  preprocessors:
    ustc-tfc2016-capsule:
      method: capsule
      dataset: ustc-tfc2016
      number-workers: 2
      kwargs:
        M: 20
        N: 1000


local:
  datasets:
    ustc-tfc2016:
      root-path: ./datasets/USTC-example
  preprocessors:
    ustc-tfc2016-capsule:
      method: capsule
      dataset: ustc-tfc2016
      output-path: ./datasets/USTC-example-capsule-20-1000
  glads:
    datasets:
      root-path: ./datasets/example
      output-path: ./datasets/example-output
  # Capsule 胶囊网络的实验数据集预处理
  capsule:
    datasets:
      # UTSC M = 20, N = 1000 的预处理
      - name: USTC-Capsule
        # 数据集所在位置
        root-path: ./datasets/USTC-example
        # 预处理输出位置
        output-path: ./datasets/USTC-example-capsule-20-1000
        # 参数 M 和 N
        M: 20
        N: 1000

# 以下是服务器的环境
school-server:
  glads:
    dataset-path:
  capsule:
    datasets:
      - name: USTC-TFC2016-Capsule-20-1000
        root-path: /home/wangc/datasets/USTC-TFC2016
        output-path: /home/wangc/datasets/USTC-TFC2016-Capsule-20-1000
        # 参数
        M: 20
        N: 1000
